name: nft_museum
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_smart_retry: ^1.0.0
  lottie: ^1.3.0
  cached_network_image: ^3.2.1
  google_fonts: ^3.0.1
  toggle_switch: ^2.0.1
  flutter_web_browser: ^0.17.1
  readmore: ^2.2.0
  get: ^4.6.5
  http_interceptor: ^1.0.2
  animations: ^2.0.3
  shared_preferences: ^2.0.12
  flutter_easyloading: ^3.0.5
  custom_pop_up_menu: ^1.2.4
  glassmorphism: ^3.0.0
  shimmer: ^2.0.0
  video_player: ^2.4.7
#  bitsdojo_window: ^0.1.2
#  confetti: ^0.7.0
  flutter_svg: ^1.1.0
#  custom_pop_up_menu: ^1.2.4
  animated_background:
  flutter_staggered_animations: ^1.0.0
#  animated_text_kit: ^4.2.2
  qlevar_router: ^1.5.9
  rive: ^0.9.1
  audioplayers: ^1.0.1
#  just_audio: ^0.9.28
  #  window_size:
  #    git:
  #      url: https://github.com/google/flutter-desktop-embedding.git
  #      path: plugins/window_size


  url_launcher: ^6.0.12
  qr_flutter: ^4.0.0
  #  web3dart:
  #  dart_web3:
  #  flutter_web3:
  #  walletconnect_dart: ^0.0.3
  #  flutter_web3:

  # web3dart
#  build: ^2.0.0
#  build_config: ^1.0.0
#  dart_style: ^2.0.0
#  code_builder: ^4.0.0
#  path: ^1.8.0
#  built_collection: ^5.0.0
  pointycastle: ^3.4.0
#  convert: ^3.0.0
#  js: ^0.6.3
#  uuid: ^3.0.1
#  typed_data: ^1.1.6
#  stream_channel: ^2.0.0
#  stream_transform: ^2.0.0
  json_rpc_2: ^3.0.0

  #walletconnect
#  web_socket_channel: ^2.1.0
  cryptography: ^2.0.5
#  json_annotation: ^4.4.0
#  stack_trace: ^1.10.0


#  flutter_ipfs: ^0.0.2
#  ipfs_client_flutter: ^1.0.7
#  https://github:com/hackyguru/IPFS-Flutter:



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.2
  pedantic: ^1.11.0
  build_runner: ^2.0.3
  flutter_gen_runner: ^4.1.6
  build_test: ^2.1.0
  test: ^1.9.0
  coverage: ^1.1.0
  flutter_lints: ^2.0.0


flutter_gen:
  output: lib/core/gen/ # Optional (default: fluttermap/gen/)
  line_length: 80 # Optional (default: 80)


  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

flutter:
  fonts:
    - family: harry
      fonts:
        - asset: assets/fonts/harry_potter.ttf
    - family: s1
      fonts:
        - asset: assets/fonts/s1.otf
    - family: s2
      fonts:
        - asset: assets/fonts/a2.otf
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/fonts/
    - assets/rive/
    - assets/songs/
    - assets/videos/
