name: administrator_nft_market
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  dio: ^4.0.4
  http_interceptor: ^1.0.2
  animations: ^2.0.3
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.12
  flutter_gen_runner: ^4.1.6
  flutter_easyloading: ^3.0.5
  curved_navigation_bar: ^1.0.3
  flutter_staggered_animations: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
